/**
 * @file create_asset.js
 * @description Create a new asset in Brandfolder. 
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;

module.exports = function create_asset (app, body) {
  const {
    token
  } = body.payload.registrationData;

  /** @type {String} name Name of the asset.  */
  const {
    name,
    description,
    attachments,
    primary_attachment,
    section_id,
    placeholder_text,
    font_color,
    background_color,
    h_size,

    
    v_size
  } = body.payload.moduleParam;

  if (token != undefined) { 
    /** @type {ModuleResponse} response The Converse AI response to respond with. */
    const response = new ModuleResponse();

    
  
    response.setValue({});
    app.send(Status.SUCCESS, response);
  } else { 
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' }); 
  }
};
