/**
 * @file list_users.js
 * @description List Users  
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;
const fetch         = require('node-fetch');

module.exports = function list_users (app, body) {
  const {
    token,
    org_id
  } = body.payload.registrationData;

  
  if (token != undefined && org_id != undefined) { 
    const response = new ModuleResponse();

    const options = {
      method: 'GET',
      headers:{
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      json: true
    }

    fetch(`https://brandfolder.com/api/v4/organizations/${org_id}`, options).then(result => {
      response.setValue(result);
      app.send(Status.SUCCESS, response);
    }).catch(err => {
      console.error(err)
      app.fail({ httpStatus: err.statusCode, message: err.error.errors}); 
    })
  } else { 
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' }); 
  }
};
