/**
 * @file list_tags.js
 * @description Lists all tags in Brandfolder 
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;
const fetch           = require('node-fetch');

module.exports = function list_tags(app, body) {
  const {
    token,
    brandfolder_id
  } = body.payload.registrationData;

  
  if (token != undefined && brandfolder_id != undefined) { 
    const response = new ModuleResponse();

    const options = {
      method: 'GET',
      headers:{
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      }
    }
    
    fetch(`https://brandfolder.com/api/v4/brandfolders/${brandfolder_id}/searchable_things`, options).then(result => {
      return result.json()
    }).then(result => { 
      response.setValue({ result: result.tags });
      app.send(Status.SUCCESS, response);
    }).catch(err => {
      console.error(err)
      app.fail({ httpStatus: err.statusCode, message: err.error.errors}); 
    })
  } else { 
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' }); 
  }
};
